/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<
      'index',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '404-fallback': RouteRecordInfo<
      '404-fallback',
      '/:fallback(.*)',
      { fallback: ParamValue<true> },
      { fallback: ParamValue<false> },
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | '/admin/'
      | '/admin/buckets'
      | '/admin/settings'
      | '/admin/users'
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/buckets': RouteRecordInfo<
      '/admin/buckets',
      '/admin/buckets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/settings': RouteRecordInfo<
      '/admin/settings',
      '/admin/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'auth-login': RouteRecordInfo<
      'auth-login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'auth-register': RouteRecordInfo<
      'auth-register',
      '/auth/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'bucket-root': RouteRecordInfo<
      'bucket-root',
      '/bucket',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'bucket-browse': RouteRecordInfo<
      'bucket-browse',
      '/bucket/:bucket/:path(.*)?',
      { bucket: ParamValue<true>, path?: ParamValueZeroOrOne<true> },
      { bucket: ParamValue<false>, path?: ParamValueZeroOrOne<false> },
      | never
    >,
    '@upload-standalone': RouteRecordInfo<
      '@upload-standalone',
      '/bucket/:bucket/@upload',
      { bucket: ParamValue<true> },
      { bucket: ParamValue<false> },
      | never
    >,
    'preferences': RouteRecordInfo<
      'preferences',
      '/preferences',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'frontend/pages/index.vue': {
      routes:
        | 'index'
      views:
        | never
    }
    'frontend/pages/[...fallback].vue': {
      routes:
        | '404-fallback'
      views:
        | never
    }
    'frontend/pages/admin.vue': {
      routes:
        | '/admin'
        | '/admin/'
        | '/admin/buckets'
        | '/admin/settings'
        | '/admin/users'
      views:
        | 'default'
    }
    'frontend/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
    }
    'frontend/pages/admin/buckets.vue': {
      routes:
        | '/admin/buckets'
      views:
        | never
    }
    'frontend/pages/admin/settings.vue': {
      routes:
        | '/admin/settings'
      views:
        | never
    }
    'frontend/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
    }
    'frontend/pages/auth/login.vue': {
      routes:
        | 'auth-login'
      views:
        | never
    }
    'frontend/pages/auth/register.vue': {
      routes:
        | 'auth-register'
      views:
        | never
    }
    'frontend/pages/bucket/index.vue': {
      routes:
        | 'bucket-root'
      views:
        | never
    }
    'frontend/pages/bucket/[bucket]/[[...path]].vue': {
      routes:
        | 'bucket-browse'
      views:
        | never
    }
    'frontend/pages/bucket/[bucket]/@upload.vue': {
      routes:
        | '@upload-standalone'
      views:
        | never
    }
    'frontend/pages/preferences.vue': {
      routes:
        | 'preferences'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
